file_format: "1"
id: ergoflowwing01
name: "ErgoFlow Wing v01"
type: shield
url: https://github.com/MakotoKurauchi/ergoflowwing01
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - ergoflowwing01_left
  - ergoflowwing01_right
